# This workflow will run unit tests

name: Test Skill
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
  skill_unit_tests:
    uses: neongeckocom/.github/.github/workflows/skill_tests.yml@master
    with:
      resource_file: tests/test_resources.yaml
  skill_intent_tests:
    uses: neongeckocom/.github/.github/workflows/skill_test_intents.yml@master
    with:
      resource_file: tests/test_intents.yaml
  skill_resource_tests:
    uses: neongeckocom/.github/.github/workflows/skill_test_resources.yml@master
    with:
      resource_file: tests/test_resources.yaml
  skill_install_tests:
    uses: neongeckocom/.github/.github/workflows/skill_test_installation.yml@master
